### ISSUE TITLE
Configuration in nginx.j2

### ISSUE THREAD

**Issue by amenophis** [Elao/ansible-role-php#1]
Hi,
Do you plan to add a way to allow configuration inside the nginx.j2 template ?

Would be nice to use the following value inside:
```
 elao_php_fpm_pools:                           # Fpm pools
  www: 
    listen: "127.0.0.1:9000" # or "unix:/var/run/php5-fpm.sock"
```

Would be nice to change the value of each other parameters.

What do you think ?

**Comment by nervo** [comment]
We plan to handle such things (in fact, it's already done :) ), but only on our refactored roles.
Stay tuned :)

**Comment by amenophis** [comment]
:)
How many time ??

**Comment by nervo** [comment]
Summer is coming !

Let's say one or two weeks :)

**Comment by amenophis** [comment]
ok :)
